version: "3.8"
services:
  attacker:
    build:
      context: .
      dockerfile: attacker.Dockerfile
    hostname: attacker-vm
    ports:
      - "1020:22" #change this when hosting
    networks:
      external:
        ipv4_address: 192.168.101.99
  dmz_web:
    build:
      context: .
      dockerfile: dmz-web.Dockerfile
    hostname: dmz-web
    ports:
      - "4444"
    networks:
      external:
        ipv4_address: 192.168.101.5
      internal:
        ipv4_address: 192.168.150.5
  internal_web:
    build:
      context: .
      dockerfile: internal-web.Dockerfile
    hostname: internal-web
    ports:
      - "1337"
    networks:
      internal:
        ipv4_address: 192.168.150.10   
      
networks:
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
          gateway: 192.168.101.1
  internal:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.150.0/24
        gateway: 192.168.150.1
  
